services:
  app:
    build: .
    ports:
      - "7577:7577"
    environment:
      - DB_PASSWORD=34315203
      - JWT_SECRET=qwertyuioplkjhgfdsazxcvbnm
      - DOCKER_ENV=true
    depends_on:
      - db
    restart: unless-stopped  

  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=34315203
      - POSTGRES_DB=shope_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: